### ISSUE TITLE
Bug with the electrical alert

### ISSUE THREAD

**Issue by tchavre** [KSP-RO/TacLifeSupport#89] opened 2017-06-07 22:11 UTC
the mod T A C have a bug , it always give an alert elctric charge depeleted but allmy chips have the batteries full, maybe he dont calculate the solair panel . the probleme is a lot of wrong alert could forget a reel alert on a ship.
sorry for my bad english
 thank you for this good mod bye

**Comment by JPLRepo** [comment] 2017-06-08 09:59
Do you have BackgroundProcessing mod installed as is suggested in the thread on the forum?

**Comment by tchavre** [comment] 2017-06-09 13:46
hello , i don t know, maybe not, were i can find this background Processing?

**Comment by tchavre** [comment] 2017-06-09 20:12
it was not easy but i found background processing, after instaling , it dosn t work , always the wrong alert.
i have an other probleme , maybe it work with? when the module manager load the game , y found 2 errors in the file of the mod UmbraSpaceIndustries MKS /patch/ TAC-LS .CFG . if you can read this. thanks
[TAC-LS.txt](https://github.com/KSP-RO/TacLifeSupport/files/1065139/TAC-LS.txt)

**Comment by JPLRepo** [comment] 2017-06-09 20:27
I'm working on the EC problem. But I have two paid jobs. and mods are not paid, they are in my free time.

That other problem is a problem with MKS mod. Nothing to do with TAC LS.

**Comment by tchavre** [comment] 2017-06-09 20:54
it s not urgent for my, and i understand it not easy to repar this bug, TAC LS is a great mod for me , i wait for a patch to fix this. without this bug it s perfect

**Comment by JPLRepo** [comment] 2017-06-13 20:28
Try the dev build.
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.3dev

**Comment by JPLRepo** [comment] 2017-07-03 09:45
Looks like a duplicate of bug #90

**Comment by JPLRepo** [comment] 2017-07-30 04:18
Please try dev build from this link:
https://github.com/KSP-RO/TacLifeSupport/releases/tag/v0.13.4dev

**Closed as completed** 2017-08-12 09:14 UTC
Labels: Ready to Implement

**Comment by inoculator** [comment] 2018-12-27 22:37
Hi there,
I dare to open a new issue in a known bug, even so it seems to be closed.
I am running KSP 1.3.1 using CKAN for Modding and Version 0.13.6.0 of TAC Life Support is installed.
The BUG from above hit me on this.
Question is: Where is the information stored about the value displayed or calculated.
My target: Edit some file and change the miscalculated value, reload the game and be happy.
Is this possible or is my game doomed to this failure?
