### ISSUE TITLE
Food consumption

### ISSUE THREAD

**Issue by YourAgony** [KSP-RO/TacLifeSupport#112] opened 2018-04-24 20:24 UTC
Hi, i have a Space Station with Food for 11 J and 365 days ( only 6 Kerbals on Board ) but the foot runs out after 5 to 6 days.... i think there is something wrong ... in Settings Food and water consumption are nearly the same, but i lost Food that should be enough for days in only one Minute....

only Food all other Things are normal.... the time is running and runnig....

please help

**Comment by JPLRepo** [comment] 2018-07-16 01:53
You provide very little information...
Please provide: More information about the vessel and what was the situation when it ran out? What scene were you in? Tracking station? KSC?, Flight? Did you use timewarp at the time; or what?
Please provide: Save game with the vessel in question. OF course if the save game contains other mods.. I probably can't help much.

**Comment by JPLRepo** [comment] 2020-02-08 04:04
No new information supplied for a year and a half. Closing.

**Closed as completed by JPLRepo** 2020-02-08 04:04 UTC
Labels: More Information Required

**Comment by ThijmenDF** [comment] 2021-10-16 14:48
Hi, I know it's not ideal to dig up old issues, but I'm experiencing the same problems as the OP.

The problem seems to be that the hydrophonics modules from SSPXR will consume a crazy amount of food while active, if the vessel is unloaded in all situations (controlling other vessels, at the KSC, in the tracking station). Timewarp does not change this (it consumes it faster during timewarp).

They work as intended when the vessel is loaded.

Here's a screenshot. This station is 2 days old and launched with a crew of 2 (which would provide them with more than a year of supplies with default settings):

![image](https://user-images.githubusercontent.com/2705853/137591611-bc33d94e-368d-47fe-8e96-62c88fc13b27.png)

The food was consumed fully in 2 days, starting when I went back to the KSC and started time-warping.

Unfortunately I'm playing with a pretty heavy mod list, but TAC LS is the only one of its kind.

Most important mods:
TAC LS 0.18.0.0
SSPXR 2.0.5
BackgroundResources 0.18.0.0
DeepFreeze Continued 0.31.0.0
Ship Manifest 6.0.2.0

**Comment by ThijmenDF** [comment] 2021-10-16 15:55
A quick update - I updated the `SSPXR-TACLS-00.cfg` file that comes with SSPXR. I changed line 157, which changes how the Mineral Siphon feature of the greenhouseswork. I set the Food input to 0.0. This made the greenhouse no longer consume minerals like crazy. 

**Even though Mineral Siphon is off** it seems that Mineral Siphon is being counted during the background processes **instead** of the SETI greenhouse feature.

```
	// Mineral Siphon
	MODULE
	{
		// Uses CRP Minerals instead of own custom Nutrient resource.
		// Food or Nutrient to Mineral ratio is 960.7547:1
		// Siphon's Food intake rate scaled to ratio.
		// Greenhouse's Mineral intake rate scaled to ratio.

		name = TacGenericConverter
		ConverterName = #LOC_SSPXR_Switcher_TacGenericConverter7_ConverterName // Mineral Siphon
		StartActionName = #LOC_SSPXR_Switcher_TacGenericConverter7_StartActionName // Start Mineral Siphon
		StopActionName = #LOC_SSPXR_Switcher_TacGenericConverter7_StopActionName // Stop Mineral Siphon
		tag = #LOC_SSPXR_Switcher_TacGenericConverter_tag // Life Support
		GeneratesHeat = false
		conversionRate = 1
		INPUT_RESOURCE
		{
			ResourceName = Food
			Ratio = 0.0
		}
```

**Comment by JonnyOThan** [comment] 2023-09-19 07:27
I have a hunch that this might be related to https://github.com/JonnyOThan/RasterPropMonitor/issues/93 .  Namely, the stock ModuleResourceConverter’s Recipe property will cache its recipe the first time it is called and will never change again.  If that happens before other things have a chance to set it up, it could break.
